#!/bin/sh

bspc config border_width	1
bspc config window_gap		5

bspc config top_padding		0
bspc config right_padding	0
bspc config left_padding	0
bspc config bottom_padding	0

bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focus_follows_pointer	false
bspc config click_to_focus			true
bspc config split_ratio				0.50
bspc config focused_border_color    "#FFFFFF"

bspc rule -a Conky sticky=off manage=off lower=on

WP=$HOME/Pictures/woods.jpg

if [[ $(hostname) == 'pc' ]]; then
    xrandr \
		--output DP-4 --mode 2560x1440 --rate 143.91 --primary --pos 1080x0 \
		--output DVI-D-0 --mode 1920x1080 --pos 0x-130 --rotate right \
		--output HDMI-0 --mode 1920x1080 --pos 3640x-130 --rotate left
    
	bspc monitor DVI-D-0 -d 1 2 3
	bspc monitor DP-4 -d 4 5 6
	bspc monitor HDMI-0 -d 7 8 9

	bspc rule -a Chromium desktop='^1' state=fullscreen
	bspc rule -a Rambox desktop='^7' state=floating
	bspc rule -a Code desktop='^4'

	feh --bg-fill $WP $WP $WP
fi

if [[ $(hostname) == 'laptop' ]]; then
    xrandr \
		--output eDP-1 --mode 1920x1080 --rate 143.91 --primary --pos 0x0 \
		--output HDMI-1 --mode 2560x1080 --pos 1920x0
    
	bspc monitor eDP-1 -d 1 2 3
	bspc monitor HDMI-1 -d 4 5 6

	bspc rule -a Chromium desktop='^4'
	bspc rule -a Rambox desktop='^1' state=floating
	bspc rule -a Code desktop='^4'

	feh --bg-fill $WP $WP
fi

source ~/.xprofile &
