#!/bin/sh

bspc config border_width	1
bspc config window_gap		5

bspc config top_padding		0
bspc config right_padding	0
bspc config left_padding	0
bspc config bottom_padding	0

bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focus_follows_pointer	false
bspc config click_to_focus			true
bspc config split_ratio				0.50
bspc config focused_border_color    "#FFFFFF"

bspc rule -a Gnome-calculator state=floating

WP=$HOME/Pictures/Wallpapers/leaves.jpg

if [[ $(hostname) == 'pc' ]]; then
    xrandr \
        --output DP-4 --mode 2560x1440 --rate 143.91 --primary --pos 1080x0 \
	--output DVI-D-0 --mode 1920x1080 --pos 0x-130 --rotate right \
	--output HDMI-0 --mode 1920x1080 --pos 3640x-130 --rotate left

    bspc monitor DVI-D-0 -d 1 2 3
    bspc monitor DP-4 -d 4 5 6
    bspc monitor HDMI-0 -d 7 8 9

    bspc desktop 1 -l monocle

    bspc rule -a Rambox desktop='^7' state=floating rectangle=1060x800+10+1110
fi

if [[ $(hostname) == 'laptop' ]]; then
    xrandr --newmode "1680x1050_60.00"  147.14  1680 1784 1968 2256  1050 1051 1054 1087  -HSync +Vsync
    xrandr --addmode DVI-I-1-1 1680x1050_60.00
    xrandr \
        --output eDP1 --mode 1920x1080 --rate 143.91 --primary --pos 0x0 \
	--output HDMI1 --mode 2560x1080 --pos 1920x0 \
	--output DVI-I-1-1 --mode 1680x1050_60.00 --pos 4480x0

    bspc monitor eDP1 -d 1 2 3
    bspc monitor HDMI1 -d 4 5 6
    bspc monitor DVI-I-1-1 -d 7 8 9

    bspc rule -a Rambox desktop='^1' state=floating
fi

feh --bg-fill $WP $WP $WP

source ~/.xprofile &
