#!/bin/sh

bspc config border_width	1
bspc config window_gap		5
bspc config top_padding		0
bspc config right_padding	0
bspc config left_padding	0
bspc config bottom_padding	0

bspc config borderless_monocle          true
bspc config pointer_follows_monitor     true
bspc config pointer_follows_focus       true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       false
bspc config click_to_focus              true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

bspc config split_ratio			    0.50
bspc config focused_border_color    "#FFFFFF"

bspc rule -a Gnome-calculator state=floating

if [[ $(hostname) == 'pc' ]]; then
    xrandr \
    	--output DP-4 --mode 2560x1440 --rate 143.91 --primary --pos 1080x0 \
		--output DP-3 --mode 1920x1080 --pos 0x-130 --rotate left \
		--output DP-1 --mode 1920x1080 --pos 3640x-130 --rotate right

    bspc monitor DP-3 -d 1 2 3
    bspc monitor DP-4 -d 4 5 6
    bspc monitor DP-1 -d 7 8 9

    bspc desktop 1 -l monocle
    bspc rule -a Rambox desktop='^7' state=floating rectangle=1060x800+10+1110
fi

if [[ $(hostname) == 'laptop' ]]; then
    autorandr --change --default default
fi

~/.config/autorandr/postswitch.d/wallpaper &

source ~/.xprofile &
